name: API Tests

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      tagsInclude:
        description: "Tags to include (comma-separated)"
        required: false
        default: "Regression"
      tagsExclude:
        description: "Tags to exclude (comma-separated)"
        required: false
        default: "Flaky"
      tests:
        description: "Test classes to run (comma-separated)"
        required: false
        default: "BasicToAdvancedEvolutionTest,AdvancedExamplesTest"
  pull_request:
    branches: [main]
    paths:
      - "api-test-framework/**"

jobs:
  run:
    uses: CyborgCodeSyndicate/roa-github-workflows/.github/workflows/roa-tests.yml@v1.0.0-rc-2
    with:
      kind: api
      project_module: api-test-framework
      tags_include: ${{ github.event.inputs.tagsInclude || 'Regression' }}
      tags_exclude: ${{ github.event.inputs.tagsExclude || 'Flaky' }}
      max_runners: 1
      mvn_extra_test_args: >-
        -Dtest=${{ github.event.inputs.tests || 'BasicToAdvancedEvolutionTest,AdvancedExamplesTest' }}
    secrets:
      maven_user:  ${{ secrets.GH_PACKAGES_USER }}
      maven_token: ${{ secrets.GH_PACKAGES_PAT }}
